### ISSUE TITLE
taro引入svg-sprite-loader后编译h5运行的html中未生成symbol，svg图片不显示。

### ISSUE THREAD

**Issue by luoyu-china** [NervJS/taro-issue-helper#13]
![image](https://user-images.githubusercontent.com/57477552/122526217-a3417500-d04c-11eb-9bec-2d215489ebfc.png)
![image](https://user-images.githubusercontent.com/57477552/122526242-a9cfec80-d04c-11eb-9eeb-95b675453250.png)

**Comment by Chen-jj** [comment]
@luoyu-china 到 taro 主仓库提一下咯

**Comment by luoyu-china** [comment]
> @luoyu-china 到 taro 主仓库提一下咯

提过了，这里 https://github.com/NervJS/taro/issues/9566
